# +--------------------------------------+
# | Slider                               |
# +--------------------------------------+
number:
  - platform: template
    name: "Max charge voltage"
    id: "max_charge_voltage"
    step: 10
    min_value: 3450
    max_value: 3700
    mode: slider
    initial_value: 3450
    unit_of_measurement: mV
    icon: mdi:battery-charging
    optimistic: true
    restore_value: true
    entity_category: config

  - platform: template
    name: "Float voltage"
    id: "float_voltage"
    step: 10
    min_value: 3400
    max_value: 3500
    mode: slider
    initial_value: 3400
    unit_of_measurement: mV
    icon: mdi:battery-charging
    optimistic: true
    restore_value: true
    entity_category: config
    on_value:
      then:
        - lambda: |-
            float slider_value = id(float_voltage).state;

  - platform: template
    name: "Charging current max"
    id: "charging_current"
    step: 1
    min_value: 0
    max_value: "${charge_a}"
    initial_value: "${charge_a}"
    unit_of_measurement: A
    icon: mdi:current-dc
    optimistic: true
    restore_value: true
    entity_category: config
    on_value:
      then:
        - lambda: |-
            float slider_value = id(charging_current).state;

  - platform: template
    name: "Discharging current max"
    id: "discharging_current"
    step: 1
    min_value: 0
    max_value: "${discharge_a}"
    initial_value: "${discharge_a}"
    unit_of_measurement: A
    icon: mdi:current-dc
    optimistic: true
    restore_value: true
    entity_category: config
    on_value:
      then:
        - lambda: |-
            float slider_value = id(discharging_current).state;

  - platform: template
    name: "Parallel packs capacity (Ah)"
    id: "parrallel_packs_capacity_ah"
    step: 1
    min_value: 0
    max_value: 480
    mode: slider
    initial_value: 0
    unit_of_measurement: Ah
    icon: mdi:sine-wave
    optimistic: true
    restore_value: true
    entity_category: config

  - platform: template
    name: "Over voltage protection"
    id: "can_over_voltage_protection"
    step: 5
    min_value: 3400
    max_value: 3510
    mode: slider
    initial_value: 3400
    unit_of_measurement: mV
    icon: mdi:sine-wave
    optimistic: true
    restore_value: true
    entity_category: config

  - platform: template
    name: "Under voltage protection CAN bus"
    id: "can_under_voltage_protection"
    step: 10
    min_value: 3100
    max_value: 3350
    mode: slider
    initial_value: 3150
    unit_of_measurement: mV
    icon: mdi:sine-wave
    optimistic: true
    restore_value: true
    entity_category: config

  - platform: template
    name: "Stop discharging SOC"
    id: "can_soc_stop_discharging"
    step: 1
    min_value: 10
    max_value: 50
    mode: slider
    initial_value: 20
    icon: mdi:battery-20
    optimistic: true
    restore_value: true
    entity_category: config

  - platform: template
    name: "Voltage recovery gap"
    id: "${name}_voltage_recovery_gap"
    step: 1
    min_value: 5
    max_value: 50
    mode: slider
    initial_value: 5
    icon: mdi:battery-20
    optimistic: true
    restore_value: true
    entity_category: config