text_sensor:
  - platform: jk_bms
    errors:
      name: " errors"
    operation_mode:
      name: " operation mode"
    battery_type:
      name: " battery type"
    password:
      name: " password"
    device_type:
      name: " device type"
    software_version:
      name: " software version"
    manufacturer:
      name: " manufacturer"
    total_runtime_formatted:
      name: " total runtime formatted"
  - platform: template
    name: " Charging Status"
    id: ${name}_charging_status
  - platform: template
    name: " CANBUS Status"
    id: ${name}_canbus_status