# ============================================================
# dyndns.yaml — Dynamic DNS + SNTP, config at runtime
# ============================================================

http_request:
  verify_ssl: false
  timeout: 60s

time:
  - platform: sntp
    id: my_time
    update_interval: 6h
    servers:
      - pool.ntp.org
      - time.cloudflare.com
    on_time:
      - seconds: 0
        minutes: /10
        then:
          
          - http_request.get:
              url: !lambda |-
                return "https://freemyip.com/update?token=${token}&domain=${name}.freemyip.com";
              on_response:
                then:
                  - lambda: |-
                      ESP_LOGI("DynDNS", "Status: %d domain: %s",
                        response->status_code,
                        "domain=${name}.freemyip.com");