# esphome/common/ota_http.yaml
ota:
  - platform: esphome
    password: !secret ota_password
    port: 8266

  - platform: http_request
    verify_ssl: false

http_request:
  verify_ssl: false
  timeout: 60s

button:
  - platform: template
    name: "Firmware Update"
    id: ${name}_firmware_update
    entity_category: config
    icon: mdi:cloud-download
    on_press:
      then:
        - logger.log: "OTA update starting..."
        - ota_http_request.flash:
            md5_url: http://ota.sfdp.net/homehna/firmware.md5
            url: http://ota.sfdp.net/homehna/firmware.bin