# esphome/common/ota_http.yaml
ota:
  - platform: esphome
    port: 8266
    password: !secret ota_password
    on_state_change:
      - logger.log: esphome.on_state_change

  - platform: http_request

button:
  - platform: template
    name: "Firmware Update"
    id: ${name}_firmware_update
    entity_category: config
    icon: mdi:cloud-download
    on_press:
      then:
        - logger.log: "OTA update starting..."
        - ota.http_request.flash:
            md5_url: http://ota.sfdp.net/homehna/firmware.md5
            url: http://ota.sfdp.net/homehna/firmware.bin.gz